In [34]:
import numpy as np
numbers = []
for i in range(1, 17):
    a = int(input("Enter number " + str(i) + ": "))
    numbers.append(a)
matrix = np.array(numbers).reshape(4, 4)
print(matrix)
indices_to_remove = [5, 6, 9, 10]
filtered_list = [value for index, value in enumerate(numbers) if index not in indices_to_remove]
result=1;
for x in filtered_list:
    if x!=0:
        result=x*result
print (result)


Enter number 1:  1
Enter number 2:  1
Enter number 3:  1
Enter number 4:  1
Enter number 5:  1
Enter number 6:  1
Enter number 7:  1
Enter number 8:  1
Enter number 9:  1
Enter number 10:  1
Enter number 11:  0
Enter number 12:  0
Enter number 13:  0
Enter number 14:  0
Enter number 15:  00
Enter number 16:  000


[[1 1 1 1]
 [1 1 1 1]
 [1 1 0 0]
 [0 0 0 0]]
1
